### ISSUE TITLE
dep init fails on bitbucket.org/ww/goautoneg

### ISSUE THREAD

**Issue by carolynvs** [fabulous-gopher/k8s-dep-e2e#1]
The godep config for `bitbucket.org/ww/goautoneg` has a comment of `null-5` which dep tries to convert into a constraint. When it fails, the entire init process stops. The workaround is to remove the comment.

I've opened the following (mostly related) dep issues to track:
* [Warn when an importer cannot preserve a constraint](https://github.com/golang/dep/issues/907)
* [Validate that imported locked revisions did not change after solving](https://github.com/golang/dep/issues/908)
* [Failed dep init runs should still write out config files](https://github.com/golang/dep/issues/909)

With these in place, the init run would instead:
* warn about the rejected comment and pick a new constraint.
* warn if that resulted in the final locked revision changing.
* write out a set of config files even if further unrecoverable errors were encountered.

**Comment by sdboyer** [comment]
just to note, my offhand memories of trying to convert k8s in the past put goautoneg at causing problems like maybe 40% of the time

**Comment by carolynvs** [comment]
After removing the comment, I was able to get much farther. So that's working for our little /s/staging/_staging experiment and those issues I opened in dep should prevent it from causing more trouble later. 🤞

**Comment by carolynvs** [comment]
I'm just opening issues to track what was necessary to get stuff working, but the real tracking issues for any work will live in other repos. Let me know if it's too noisy/unhelpful.

**Comment by krisnova** [comment]
These are good - I am doing my best to stay caught up

**Comment by carolynvs** [comment]
The main part of this has been fixed in the great importer rewrite of 2017 https://github.com/golang/dep/pull/1100. Import no longer picks constraints that will immediately invalidate the locked revision, and ignores junk input.

The other issues mentioned in the OP, writing out the manifest/lock on a failed run and warning when a constraint can't be honored are still open but aren't blockers.
