### ISSUE TITLE
dep init fails on for packages with multiple dashes in the version

### ISSUE THREAD

**Issue by carolynvs** [fabulous-gopher/k8s-dep-e2e#3]
I've opened an issue with deps' semver library: https://github.com/Masterminds/semver/issues/59.

When our semver lib parses the comment `v1.3.1-1-gf12c623` as a constraint, it is not returning an error, nor a valid constraint, resulting in wonky resolution like this:

```
attempt github.com/fsnotify/fsnotify with 1 pkgs; 32 versions to try
(51)      try github.com/fsnotify/fsnotify@v1.4.2
(52)  ✗   github.com/fsnotify/fsnotify@v1.4.2 not allowed by constraint :
```

This is also a problem for:
* `github.com/garyburd/redigo` @ `v1.0.0-1-gb8dc900`
* `github.com/gogo/protobuf` @ `v0.4-3-gc0656edd`
* `github.com/google/cadvisor` @ `v0.26.0-2-gb971fd1`
* `github.com/jteeuwen/go-bindata` @ `v3.0.7-72-ga0ff256`
* `github.com/karlseguin/ccache` @ `v2.0.2-5-g3ba9789`
* `github.com/lpabon/godbc` @ `v1.0-1-g9577782`
* `github.com/magiconair/properties` @ `v1.7.0-4-g61b492c`
* `github.com/mistifyio/go-zfs` @ `v2.1.1-5-g1b4ae6f`
* `github.com/mvdan/xurls` @ `v0.8.0-14-g1b768d7`
* .... I give up, this is used a lot.

**Comment by sdboyer** [comment]
eeew, crap, that's super not ok. definitely a bug I'm responsible for, too 😛

**Comment by carolynvs** [comment]
If I felt bad about every bug that I was responsible for, I would have been forced to leave software a loooong time ago. 😇

**Comment by carolynvs** [comment]
Fixed via https://github.com/golang/dep/pull/938.
