### ISSUE TITLE
Import of a package without any code causes dep init to fail

### ISSUE THREAD

**Issue by carolynvs** [fabulous-gopher/k8s-dep-e2e#6]
```
(14)  ? attempt github.com/chai2010/gettext-go with 1 pkgs; at least 1 versions to try
(15)      try github.com/chai2010/gettext-go@c6fed771bfd517099caf0f7a961671fa8ed08723
(15)  ✗   "github.com/chai2010/gettext-go/gettext" imports "github.com/chai2010/gettext-go", which contains malformed code: no buildable Go source files in /Users/carolynvs/go/pkg/dep/sources/https---github.com-chai2010-gettext--go
```

The bad import in `github.com/chai2010/gettext-go` was removed, but k8's is still locked to a revision where the bad import existed.

@sdboyer  This was run into before, see your comment https://github.com/golang/dep/issues/170#issuecomment-298147984, but it's not clear what the resolution should be?

**Comment by sdboyer** [comment]
i think my point there was sorta that there _isn't_ a resolution - if something is importing a package that lacks any working go code, that's a problem. we don't pull in `// +build ignore`'d main imports anymore, so that shouldn't be an issue.

**Comment by carolynvs** [comment]
Thanks, I'll use a later revision, where the import has been fixed.
